//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriTbaniProje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeriTabaniFasonTakipEntities : DbContext
    {
        public VeriTabaniFasonTakipEntities()
            : base("name=VeriTabaniFasonTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblCodeOlustur> TblCodeOlustur { get; set; }
        public virtual DbSet<TblIslemNo> TblIslemNo { get; set; }
        public virtual DbSet<TblKullanici> TblKullanici { get; set; }
        public virtual DbSet<TblKumasci> TblKumasci { get; set; }
        public virtual DbSet<TblUrun> TblUrun { get; set; }
        public virtual DbSet<TblGrup> TblGrup { get; set; }
        public virtual DbSet<TblSatis> TblSatis { get; set; }
        public virtual DbSet<TblFirma> TblFirma { get; set; }
        public virtual DbSet<TblAtolye> TblAtolye { get; set; }
        public virtual DbSet<TblKesimhane> TblKesimhane { get; set; }
        public virtual DbSet<TblYikama> TblYikama { get; set; }
        public virtual DbSet<TblFasonFirmalar> TblFasonFirmalar { get; set; }
        public virtual DbSet<TblFisNo> TblFisNo { get; set; }
        public virtual DbSet<TblUrunTakip> TblUrunTakip { get; set; }
        public virtual DbSet<TblAtolyeTakip> TblAtolyeTakip { get; set; }
        public virtual DbSet<TblYikamaTakip> TblYikamaTakip { get; set; }
    }
}
