//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriTbaniProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAtolyeTakip
    {
        public int AtolyeId { get; set; }
        public string FirmaBilgisi { get; set; }
        public string FirmaAdi { get; set; }
        public string Model { get; set; }
        public string Cinsi { get; set; }
        public Nullable<int> KesimAdet { get; set; }
        public string Kumasci { get; set; }
        public string KumasAdi { get; set; }
        public string TeslimAlanAdi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string FisNo { get; set; }
    }
}
