//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriTbaniProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAtolye
    {
        public int Id { get; set; }
        public string AtolyeAdi { get; set; }
        public string AtolyeTel { get; set; }
        public string AtolyeAdres { get; set; }
        public string AtolyeSahip { get; set; }
    }
}
