//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriTbaniProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFirma
    {
        public int FirmaId { get; set; }
        public string FirmaAdi { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string FirmaSahip { get; set; }
        public string E_Mail { get; set; }
    }
}
