//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriTbaniProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKullanici
    {
        public int Id { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public string E_mail { get; set; }
        public string Adi { get; set; }
        public string SoyAdi { get; set; }
        public string Telefon { get; set; }
    }
}
