//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriTbaniProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKesimhane
    {
        public int Id { get; set; }
        public string KhAdi { get; set; }
        public string KhTel { get; set; }
        public string KhAdres { get; set; }
        public string KhSahip { get; set; }
    }
}
