//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriTbaniProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUrun
    {
        public int UrunId { get; set; }
        public string UrunAdi { get; set; }
        public string UrunBilgi { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<double> SatisFiyat { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string CodeNo { get; set; }
        public string UrunGrup { get; set; }
        public string Kullanici { get; set; }
        public string FirmaAdi { get; set; }
    }
}
