//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriTbaniProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblYikama
    {
        public int Id { get; set; }
        public string YikamaAdi { get; set; }
        public string YikamaTel { get; set; }
        public string YikamaAdres { get; set; }
        public string YikamaSahip { get; set; }
    }
}
